version: '3'
services:
    validator:
        ports:
            - "1024:1024"
            - "1027:1027"
            - "8899:8899"
        image: "my-solana-validator:latest"
        env_file:
            - my-solana-validator.env
    hello-world:
        image: "my-solana-hello-world:latest"
        links:
            - validator
        env_file:
            - my-solana-hello-world.env
