FROM my-solana-base:latest
RUN pwd
RUN ls
RUN ls /home/solana/.config/solana/
RUN solana config set --url localhost
RUN solana-keygen new
RUN solana-test-validator
COPY example-helloworld /app/
RUN npm install
RUN npm build:program-rust
RUN npm build:program-c
RUN solana program deploy dist/program/helloworld.so
ENTRYPOINT [ "npm", "run", "start" ]