FROM ubuntu:bionic
WORKDIR /app
RUN apt-get update
RUN apt-get -y install curl
RUN curl https://nodejs.org/download/release/v14.18.2/node-v14.18.2-linux-x64.tar.gz
RUN tar xf node-v14.18.2-linux-x64.tar.gz
ENV PATH="/app/node-v14.18.2-linux-x64/bin:${PATH}"
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
RUN sh -c "$(curl -sSfL https://release.solana.com/v1.9.4/install)"